import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { StringEnum } from "@earendil-works/pi-ai";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

const ROOT = process.cwd();
const CONFIG = join(ROOT, ".pi", "rp-data-tools.json");
const SETTINGS = join(ROOT, "data", "rp-life-system-tree", "settings.json");
const EXCHANGE_SETTINGS = join(ROOT, "data", "rp-exchange", "settings.json");
const GLOBAL_GRAPH = join(ROOT, "data", "rp-life-system-tree", "global-graph.json");
const TEMPLATE = join(ROOT, ".pi", "skills", "rp-combat", "framework", "card-template", "unified-character-v1", "progression", "life-system-tree.json");

type Action = "init" | "status" | "graph" | "search" | "generate-node" | "audit-source" | "validate-node" | "quote-node" | "unlock" | "upgrade" | "self-achieve" | "grant-points" | "validate";
type OutputMode = "status" | "tree" | "full";

const Params = Type.Object({
  action: StringEnum(["init", "status", "graph", "search", "generate-node", "audit-source", "validate-node", "quote-node", "unlock", "upgrade", "self-achieve", "grant-points", "validate"] as const, { description: "Life System Tree action" }),
  card: Type.Optional(Type.String({ description: "Registered card key or directory path. Default: protagonist" })),
  cardPath: Type.Optional(Type.String({ description: "Directory card path relative to project root" })),
  enabled: Type.Optional(Type.Boolean({ description: "For init, set tree enabled" })),
  protagonistOverall: Type.Optional(Type.Any({ description: "Current protagonist overall N rating. Defaults N0 if combat rating not readable" })),
  query: Type.Optional(Type.String({ description: "Search text" })),
  category: Type.Optional(Type.String({ description: "Search category" })),
  worldId: Type.Optional(Type.String({ description: "Search source world id" })),
  layer: Type.Optional(Type.Any({ description: "Search layer/rating e.g. N3" })),
  node: Type.Optional(Type.Any({ description: "Life tree node object for generate-node/validate-node" })),
  nodeId: Type.Optional(Type.String({ description: "Node id for quote/unlock/upgrade/self-achieve" })),
  sourceAudit: Type.Optional(Type.Any({ description: "Source audit record" })),
  amount: Type.Optional(Type.Number({ description: "Reward point amount" })),
  pointLevel: Type.Optional(Type.Number({ description: "Reward point level" })),
  sourceType: Type.Optional(Type.String({ description: "Grant source: defeatStrongEnemy/worldImpact/plotDeviation" })),
  reason: Type.Optional(Type.String({ description: "Grant/self-achieve reason" })),
  eventRef: Type.Optional(Type.String({ description: "Memory/event reference" })),
  evidenceRef: Type.Optional(Type.String({ description: "Memory evidence for self-achieve" })),
  cardModuleUpdates: Type.Optional(Type.Array(Type.String())),
  memoryUpdates: Type.Optional(Type.Array(Type.String())),
  dryRun: Type.Optional(Type.Boolean()),
  backup: Type.Optional(Type.Boolean()),
  outputMode: Type.Optional(StringEnum(["status", "tree", "full"] as const, { description: "Mutation output mode. Default status returns only success/failure and minimal metadata; tree returns hierarchical summaries; full returns the complete legacy payload." })),
  maxBytes: Type.Optional(Type.Number())
});

const N_LABELS = ["N0 普通人级", "N1 街头级", "N2 墙壁级", "N3 房屋级", "N4 建筑级", "N5 街区级", "N6 城镇级", "N7 城市级", "N8 山脉/区域级", "N9 国家/大陆板块级", "N10 大陆级", "N11 月球/小行星级", "N12 行星级", "N13 大行星/恒星表层级", "N14 恒星级", "N15 星系级", "N16 星系团级", "N17 可观测宇宙级", "N18 单体宇宙级", "N19 多宇宙级", "N20 大型多元宇宙级", "N21 无限多元宇宙级", "N22 高维多元级", "N23 复杂高维结构级", "N24 外层/超维叙事结构级"];
const ALLOWED_NODE_KINDS = new Set(["abilityBase", "single", "multiRank", "keystone"]);
const ALLOWED_ORIGIN_TYPES = new Set(["protagonist_baseline", "canon_source", "archived_world_source", "verified_external_source", "in_story_training", "story_event_awakened", "hybrid_training_currency"]);
const FORBIDDEN_GRANT_HINTS = ["资源转换", "出售", "卖出", "献祭", "金钱购买", "购买", "刷", "普通任务", "日常训练", "重复劳动"];
const ALLOWED_GRANT_SOURCES = new Set(["defeatStrongEnemy", "worldImpact", "plotDeviation"]);

function readJson(file: string): any { return JSON.parse(readFileSync(file, "utf8")); }
function writeJson(file: string, value: any): void { mkdirSync(dirname(file), { recursive: true }); const tmp = file + ".tmp-" + process.pid + "-" + Date.now(); writeFileSync(tmp, JSON.stringify(value, null, 2) + "\n", "utf8"); renameSync(tmp, file); }
function rel(file: string): string { return file.replace(ROOT + "\\", "").replace(ROOT + "/", "").replace(/\\/g, "/"); }
function cap(n?: number): number { return Number.isFinite(n as number) ? Math.max(1000, Math.min(50000, Math.floor(n as number))) : 16000; }
function jsonOut(payload: unknown, details: Record<string, unknown>, max: number) { const raw = typeof payload === "string" ? payload : JSON.stringify(payload, null, 2); const total = Buffer.byteLength(raw, "utf8"); const text = total <= max ? raw : raw.slice(0, max) + `\n\n[life_tree_edit truncated: ${max}/${total} bytes shown]`; return { content: [{ type: "text" as const, text }], details: { ...details, truncation: { truncated: total > max, totalBytes: total, outputBytes: Math.min(max, total) } } }; }
function outputMode(params: any): OutputMode { return params?.outputMode === "tree" || params?.outputMode === "full" ? params.outputMode : "status"; }
function jsonByMode(params: any, fullPayload: any, statusPayload: any, treePayload: any, details: Record<string, unknown>, max: number) { const mode = outputMode(params); return jsonOut(mode === "full" ? fullPayload : mode === "tree" ? treePayload : statusPayload, { ...details, outputMode: mode }, max); }
function nodeSummary(node: any): any { if (!node) return undefined; return { id: node.id, name: node.name, nodeKind: node.nodeKind, category: node.category, layers: node.layers, pricingRating: node.evaluation?.pricingRating, sourceWorld: node.sourceWorld ? { worldId: node.sourceWorld.worldId, worldName: node.sourceWorld.worldName, status: node.sourceWorld.status, verificationStatus: node.sourceWorld.verificationStatus } : undefined }; }
function transactionSummary(tx: any): any { if (!tx) return undefined; return { id: tx.id, type: tx.type, state: tx.state, nodeId: tx.nodeId, nodeName: tx.nodeName, price: tx.price, amount: tx.amount, pointLevel: tx.pointLevel, display: tx.display, evidenceRef: tx.evidenceRef, eventRef: tx.eventRef, cardModuleUpdateCount: Array.isArray(tx.cardModuleUpdates) ? tx.cardModuleUpdates.length : undefined, memoryUpdateCount: Array.isArray(tx.memoryUpdates) ? tx.memoryUpdates.length : undefined }; }
function stateSummary(state: any): any { return { enabled: state.enabled, balanceLevels: Object.keys(state.currency?.balances || {}).filter(k => Number(state.currency.balances[k] || 0) !== 0), unlockedNodeCount: state.storyGraph?.unlockedNodes?.length || 0, selfAchievedNodeCount: state.storyGraph?.selfAchievedNodes?.length || 0, unlockedAbilityBaseCount: state.storyGraph?.unlockedAbilityBases?.length || 0, transactionCount: state.transactions?.length || 0, sourceAuditCount: state.sourceAudits?.length || 0 }; }
function fail(message: string, max: number) { return jsonOut({ ok: false, error: message }, { ok: false }, max); }
function safePath(p: string): string { if (p.includes("..") || p.startsWith("/") || /^[A-Za-z]:/.test(p)) throw new Error("Unsafe path: " + p); return join(ROOT, p); }
function backupFile(file: string): string | undefined { if (!existsSync(file)) return undefined; const dir = join(ROOT, "backup", "life-tree-edits"); mkdirSync(dir, { recursive: true }); const out = join(dir, new Date().toISOString().replace(/[:.]/g, "-") + "-" + file.split(/[\\/]/).pop()); writeFileSync(out, readFileSync(file, "utf8"), "utf8"); return out; }
function now(): string { return new Date().toISOString(); }
function id(prefix: string): string { return `${prefix}-${new Date().toISOString().replace(/[:.]/g, "-")}-${Math.random().toString(36).slice(2, 8)}`; }
function pointName(level: number): string { if (!Number.isInteger(level) || level < 1) throw new Error("pointLevel must be positive integer"); return `${level}级奖励点`; }
function parseN(value: any): number { if (typeof value === "number") { if (!Number.isInteger(value) || value < 0 || value > 24) throw new Error("Invalid N rating: " + value); return value; } if (value && typeof value === "object") return parseN(value.n ?? value.rating ?? value.overall ?? value.pricingRating); const m = String(value || "").match(/N\s*(\d{1,2})/i); if (!m) throw new Error("Invalid N rating: " + value); const n = Number(m[1]); if (!Number.isInteger(n) || n < 0 || n > 24) throw new Error("Invalid N rating: " + value); return n; }
function priceForN(nValue: any, exchangeSettings: any): any { const n = parseN(nValue); const row = exchangeSettings.priceByN[`N${n}`]; if (!row) throw new Error("Missing price for N" + n); return { n, label: N_LABELS[n], amount: row.amount, pointLevel: row.pointLevel, display: `${row.amount}个${pointName(row.pointLevel)}` }; }
function toBaseUnits(price: any, rate = 1000): number { return price.amount * (rate ** (price.pointLevel - 1)); }
function compactBasePrice(totalBase: number, rate = 1000, maxLevel = 5): any { let level = 1; for (let i = maxLevel; i >= 1; i--) { const unit = rate ** (i - 1); if (totalBase >= unit && totalBase % unit === 0) { level = i; break; } } const amount = Math.floor(totalBase / (rate ** (level - 1))); return { amount, pointLevel: level, display: `${amount}个${pointName(level)}`, baseUnits: totalBase }; }
function upgradeDeltaPrice(fromRating: any, toRating: any, exchangeSettings: any): any { const from = priceForN(fromRating, exchangeSettings), to = priceForN(toRating, exchangeSettings), rate = exchangeSettings.currency.conversionRate; const delta = toBaseUnits(to, rate) - toBaseUnits(from, rate); if (delta <= 0) throw new Error("upgrade target rating must be higher"); return { from, to, ...compactBasePrice(delta, rate, Math.max(5, to.pointLevel)) }; }
function normalizeBalances(balances: any = {}, exchangeSettings: any, maxLevel = 5): any { const rate = exchangeSettings.currency.conversionRate; const out: any = {}; for (let i = 1; i <= maxLevel; i++) out[pointName(i)] = Number(balances[pointName(i)] || 0); for (let i = 1; i < maxLevel; i++) { const k = pointName(i), next = pointName(i + 1), carry = Math.floor(out[k] / rate); if (carry > 0) { out[k] -= carry * rate; out[next] += carry; } } return out; }
function canAfford(balances: any, price: any, exchangeSettings: any): boolean { if (price.amount === 0) return true; const rate = exchangeSettings.currency.conversionRate, maxLevel = Math.max(5, price.pointLevel), b = normalizeBalances(balances, exchangeSettings, maxLevel); let total = 0; for (let level = price.pointLevel; level <= maxLevel; level++) total += b[pointName(level)] * (rate ** (level - price.pointLevel)); return total >= price.amount; }
function deductPrice(balances: any, price: any, exchangeSettings: any): any { if (!canAfford(balances, price, exchangeSettings)) throw new Error("Insufficient reward points"); const rate = exchangeSettings.currency.conversionRate, maxLevel = Math.max(5, price.pointLevel), b = normalizeBalances(balances, exchangeSettings, maxLevel); let totalBase = 0; for (let level = 1; level <= maxLevel; level++) totalBase += b[pointName(level)] * (rate ** (level - 1)); totalBase -= price.amount * (rate ** (price.pointLevel - 1)); const out: any = {}; for (let level = maxLevel; level >= 1; level--) { const unit = rate ** (level - 1); out[pointName(level)] = Math.floor(totalBase / unit); totalBase %= unit; } return out; }
function addPoints(balances: any, amount: number, pointLevel: number, exchangeSettings: any): any { if (!Number.isInteger(amount) || amount <= 0) throw new Error("amount must be positive integer"); const b = normalizeBalances(balances, exchangeSettings); b[pointName(pointLevel)] = Number(b[pointName(pointLevel)] || 0) + amount; return normalizeBalances(b, exchangeSettings); }

function loadSettings(): any { const s = readJson(SETTINGS); if (s.schema !== "rp-life-system-tree-settings-v1") throw new Error("Unsupported life tree settings"); return s; }
function loadExchangeSettings(): any { return readJson(EXCHANGE_SETTINGS); }
function loadGraph(): any { return readJson(GLOBAL_GRAPH); }
function saveGraph(graph: any, params: any): { backupPath?: string } { let b: string | undefined; if (!params.dryRun) { if (params.backup !== false) b = backupFile(GLOBAL_GRAPH); writeJson(GLOBAL_GRAPH, graph); } return { backupPath: b && rel(b) }; }
function resolveCard(params: any): { key: string; dir: string } { if (params.cardPath) return { key: params.card || params.cardPath, dir: safePath(params.cardPath) }; const wanted = params.card || "protagonist"; const cfg = existsSync(CONFIG) ? readJson(CONFIG) : {}; for (const group of [cfg.cards || {}, cfg.npcs || {}]) for (const [key, def] of Object.entries(group) as any) if (key === wanted || (def.aliases || []).includes(wanted)) return { key, dir: join(ROOT, def.path) }; if (cfg.allowUnregisteredCardFiles && !wanted.endsWith(".json")) { const rels = [wanted, wanted.startsWith("card/") || wanted.startsWith("card\\") ? wanted : join("card", wanted)]; for (const rp of rels) if (existsSync(safePath(rp))) return { key: wanted, dir: safePath(rp) }; } throw new Error("Unknown directory card: " + wanted); }
function stateFile(cardDir: string): string { return join(cardDir, "progression", "life-system-tree.json"); }
function defaultState(settings: any): any { const base = existsSync(TEMPLATE) ? readJson(TEMPLATE) : {}; return normalizeState(base, settings); }
function normalizeState(state: any, settings: any): any { state.schema = state.schema || "rp-life-system-tree-state-v1"; state.enabled = !!state.enabled; state.owner = state.owner || "protagonist-only"; state.uiStyle = state.uiStyle || "sci-fi"; state.masterGraphRef = state.masterGraphRef || "data/rp-life-system-tree/global-graph.json"; state.masterGraphVersion = state.masterGraphVersion || "v1"; state.displayPolicy = state.displayPolicy || settings.displayPolicy; state.currency = state.currency || {}; state.currency.conversionRate = state.currency.conversionRate || settings.currency.conversionRate; state.currency.defaultVisibleLevels = state.currency.defaultVisibleLevels || [1,2,3]; for (const key of ["balances","lifetimeEarned","lifetimeSpent"]) state.currency[key] = { "1级奖励点":0, "2级奖励点":0, "3级奖励点":0, ...(state.currency[key] || {}) }; state.storyGraph = state.storyGraph || {}; for (const key of ["unlockedAbilityBases","revealedNodes","availableNodes","unlockedNodes","selfAchievedNodes","visibleEdges"]) state.storyGraph[key] = Array.isArray(state.storyGraph[key]) ? state.storyGraph[key] : []; state.storyGraph.nodeRanks = state.storyGraph.nodeRanks || {}; for (const key of ["searchRecords","sourceAudits","transactions","auditLog"]) state[key] = Array.isArray(state[key]) ? state[key] : []; return state; }
function loadState(file: string, settings: any): any { if (!existsSync(file)) throw new Error("Life system tree state not found; run init first: " + rel(file)); return normalizeState(readJson(file), settings); }
function persist(file: string, state: any, params: any): { backupPath?: string } { let b: string | undefined; if (!params.dryRun) { if (params.backup !== false) b = backupFile(file); writeJson(file, state); } return { backupPath: b && rel(b) }; }

function nodeById(graph: any, nodeId: string): any { return (graph.nodes || []).find((n: any) => n.id === nodeId); }
function validateNode(node: any, settings: any): any { const errors: string[] = []; if (!node?.id) errors.push("node.id required"); if (!node?.name) errors.push("node.name required"); if (!ALLOWED_NODE_KINDS.has(node?.nodeKind)) errors.push("invalid nodeKind: " + node?.nodeKind); if (!ALLOWED_ORIGIN_TYPES.has(node?.originType)) errors.push("invalid originType: " + node?.originType); if (!node?.sourceWorld?.worldId || !node?.sourceWorld?.worldName || !node?.sourceWorld?.sourceType || !node?.sourceWorld?.verificationStatus) errors.push("sourceWorld worldId/worldName/sourceType/verificationStatus required"); if (node?.sourceWorld?.sourceType === "original") errors.push("sourceWorld.sourceType original forbidden"); if (node?.sourceWorld?.status === "unarchived" && (!Array.isArray(node.sourceWorld.webSources) || node.sourceWorld.webSources.length < 2)) errors.push("unarchived node requires two webSources"); if (node?.sourceWorld?.status === "story-confirmed" && !(node.sourceWorld.refs || []).some((r: any) => String(r).includes("memory/"))) errors.push("story-confirmed node requires memory ref"); const ev = node?.evaluation || {}; if (ev.framework !== "multi-world-combat-rating") errors.push("evaluation.framework must be multi-world-combat-rating"); if (ev.evaluationMethod !== "multi-world-evaluation-method-v1") errors.push("evaluationMethod required"); if (ev.ratingSystem !== "multi-world-rating-system-n0-n24-v1") errors.push("ratingSystem required"); if (!ev.pricingRating) errors.push("pricingRating required"); if (!ev.basis) errors.push("evaluation.basis required"); if (!Array.isArray(ev.evidence)) errors.push("evaluation.evidence array required"); if (!Array.isArray(node?.effects)) errors.push("effects array required"); if (node?.nodeKind === "abilityBase" && (!Array.isArray(node.effects) || node.effects.length < 1)) errors.push("abilityBase must have concrete effects"); const p = node?.pricing || {}; if (!p.mode) errors.push("pricing.mode required"); if (Array.isArray(p.discounts)) for (const d of p.discounts) if (Number(d.rate || 0) > 0 && !d.evidenceRef) errors.push("discount requires evidenceRef"); return { ok: errors.length === 0, errors }; }
function validateGraph(graph: any, settings: any): any { const errors: string[] = []; if (graph.schema !== "rp-life-system-tree-global-graph-v1") errors.push("global graph schema invalid"); const ids = new Set<string>(); for (const n of graph.nodes || []) { if (ids.has(n.id)) errors.push("duplicate node id: " + n.id); ids.add(n.id); const v = validateNode(n, settings); if (!v.ok) errors.push(`node ${n.id}: ${v.errors.join("; ")}`); } for (const e of graph.edges || []) { if (!e.id || !e.from || !e.to) errors.push("edge id/from/to required"); if (["navigation","category-entry","folder"].includes(e.type)) errors.push("navigation/category/folder edges forbidden"); if (e.from && !ids.has(e.from)) errors.push(`edge ${e.id}: missing from node`); if (e.to && !ids.has(e.to)) errors.push(`edge ${e.id}: missing to node`); } return { ok: errors.length === 0, errors }; }
function ratingCap(overall: any, settings: any): number { return Math.min(24, parseN(overall || "N0") + (settings.displayPolicy?.maxVisibleRatingOffsetFromProtagonistOverall || 1)); }
function nodeWithinCap(node: any, capN: number): boolean { const nums: number[] = []; for (const l of node.layers || []) nums.push(parseN(l)); if (node.evaluation?.pricingRating) nums.push(parseN(node.evaluation.pricingRating)); return nums.length > 0 && Math.min(...nums) <= capN; }
function visibleGraph(graph: any, state: any, overall: any, settings: any): any { const capN = ratingCap(overall, settings); const visible = new Set([...(state.storyGraph.unlockedNodes || []), ...(state.storyGraph.selfAchievedNodes || []), ...(state.storyGraph.revealedNodes || []), ...(state.storyGraph.availableNodes || []), ...(state.storyGraph.unlockedAbilityBases || [])]); const nodes = (graph.nodes || []).filter((n: any) => visible.has(n.id) && nodeWithinCap(n, capN)); const ids = new Set(nodes.map((n: any) => n.id)); const edges = (graph.edges || []).filter((e: any) => ids.has(e.from) && ids.has(e.to) && (state.storyGraph.visibleEdges || []).includes(e.id)); return { cap: `N${capN}`, capN, nodes, edges, policy: state.displayPolicy }; }
function searchGraph(graph: any, params: any, overall: any, settings: any): any { const capN = ratingCap(overall, settings), text = String(params.query || "").toLowerCase(); const results = (graph.nodes || []).filter((n: any) => nodeWithinCap(n, capN) && (!params.category || n.category === params.category) && (!params.worldId || n.sourceWorld?.worldId === params.worldId) && (!params.layer || (n.layers || []).some((l: any) => parseN(l) === parseN(params.layer))) && (!text || `${n.id} ${n.name} ${n.category} ${n.sourceWorld?.worldName || ""}`.toLowerCase().includes(text))); return { cap: `N${capN}`, results }; }
function priceNode(node: any, ex: any): any { const p = node.pricing || {}; if (["inherent","selfTraining","storyAchievement"].includes(p.mode)) return { amount: 0, pointLevel: 1, display: "0个1级奖励点", mode: p.mode }; if (p.mode === "upgrade-delta") return { ...upgradeDeltaPrice(p.fromRating, p.toRating, ex), mode: p.mode }; return { ...priceForN(p.toRating || node.evaluation?.pricingRating, ex), mode: p.mode || "currency" }; }
function prereq(graph: any, state: any, nodeId: string): any { const unlocked = new Set([...(state.storyGraph.unlockedNodes || []), ...(state.storyGraph.selfAchievedNodes || [])]); const missing = (graph.edges || []).filter((e: any) => e.to === nodeId && e.affectsUnlock && ["prerequisite","upgrade"].includes(e.type)).filter((e: any) => !unlocked.has(e.from)).map((e: any) => e.from); return { ok: missing.length === 0, missing }; }
function quote(graph: any, state: any, nodeId: string, ex: any, settings: any): any { const node = nodeById(graph, nodeId); if (!node) return { ok: false, errors: ["node not found: " + nodeId] }; const v = validateNode(node, settings), pr = prereq(graph, state, nodeId), price = v.ok ? priceNode(node, ex) : null; const already = (state.storyGraph.unlockedNodes || []).includes(nodeId) || (state.storyGraph.selfAchievedNodes || []).includes(nodeId); const errors = [...v.errors]; if (!pr.ok) errors.push("missing prerequisites: " + pr.missing.join(", ")); if (already) errors.push("node already unlocked/self-achieved"); return { ok: errors.length === 0, errors, nodeId, nodeName: node.name, price, afford: price ? canAfford(state.currency.balances, price, ex) : false, prerequisites: pr, node }; }
function publicStatus(state: any, graph: any, overall: any, settings: any): any { return { enabled: state.enabled, owner: state.owner, uiStyle: state.uiStyle, protagonistOverall: overall || "N0", display: visibleGraph(graph, state, overall || "N0", settings), currency: state.currency, transactions: state.transactions.map((t: any) => ({ id: t.id, type: t.type, state: t.state, nodeId: t.nodeId, price: t.price, createdAt: t.createdAt })) }; }

export default function (pi: ExtensionAPI) {
  pi.registerTool({ name: "life_tree_edit", label: "Life Tree Edit", description: "Project-local protagonist Life System Tree tool. Mutation actions default to minimal success/failure output; pass outputMode=tree for hierarchical summaries or outputMode=full for complete legacy payloads. Manages sci-fi UI visible graph, source-world audited nodes, reward-point unlock/upgrade/self-achieve, and ledger state.", parameters: Params, async execute(_id, params, _signal, _onUpdate, _ctx) {
    const max = cap(params.maxBytes);
    try {
      const settings = loadSettings(), ex = loadExchangeSettings();
      if (["validate-node", "generate-node"].includes(params.action) && !params.node) throw new Error(`${params.action} requires node`);
      if (params.action === "validate-node") { const v = validateNode(params.node, settings); return jsonOut({ ok: v.ok, action: "validate-node", validation: v }, { ok: v.ok, settingsLoaded: rel(SETTINGS) }, max); }
      if (params.action === "generate-node") { const v = validateNode(params.node, settings); if (!v.ok) throw new Error("node failed validation: " + v.errors.join("; ")); const graph = loadGraph(); if ((graph.nodes || []).some((n: any) => n.id === params.node.id)) throw new Error("node already exists in shared graph: " + params.node.id); graph.nodes = graph.nodes || []; graph.nodes.push(params.node); graph.auditLog = graph.auditLog || []; graph.auditLog.push({ id: id("audit"), at: now(), action: "generate-node", nodeId: params.node.id }); const p = saveGraph(graph, params); return jsonByMode(params, { ok: true, action: "generate-node", node: params.node, dryRun: !!params.dryRun }, { ok: true, action: "generate-node", nodeId: params.node.id, dryRun: !!params.dryRun }, { ok: true, action: "generate-node", node: nodeSummary(params.node), dryRun: !!params.dryRun, graph: { addedNodeId: params.node.id } }, { ok: true, settingsLoaded: rel(SETTINGS), ...p }, max); }
      const card = resolveCard(params), file = stateFile(card.dir);
      if (params.action === "init") { const exists = existsSync(file); const state = exists ? loadState(file, settings) : defaultState(settings); if (params.enabled !== undefined) state.enabled = !!params.enabled; state.auditLog.push({ id: id("audit"), at: now(), action: "init", enabled: state.enabled }); const p = persist(file, state, params); return jsonByMode(params, { ok: true, action: "init", file: rel(file), state, dryRun: !!params.dryRun }, { ok: true, action: "init", file: rel(file), dryRun: !!params.dryRun }, { ok: true, action: "init", file: rel(file), summary: stateSummary(state), dryRun: !!params.dryRun }, { ok: true, settingsLoaded: rel(SETTINGS), ...p }, max); }
      const state = loadState(file, settings), graph = loadGraph(), overall = params.protagonistOverall || "N0";
      if (params.action === "status") return jsonOut({ ok: true, action: "status", file: rel(file), display: publicStatus(state, graph, overall, settings) }, { ok: true, settingsLoaded: rel(SETTINGS) }, max);
      if (params.action === "graph") return jsonOut({ ok: true, action: "graph", graph: visibleGraph(graph, state, overall, settings) }, { ok: true }, max);
      if (params.action === "search") { const result = searchGraph(graph, params, overall, settings); state.searchRecords.push({ id: id("search"), at: now(), query: params.query, category: params.category, worldId: params.worldId, layer: params.layer, resultIds: result.results.map((n: any) => n.id) }); const p = persist(file, state, params); return jsonOut({ ok: true, action: "search", search: result, note: "Only audited real nodes within protagonist overall+1 are returned; no hidden silhouettes or navigation nodes." }, { ok: true, ...p }, max); }
      if (params.action === "quote-node") { if (!params.nodeId) throw new Error("quote-node requires nodeId"); const q = quote(graph, state, params.nodeId, ex, settings); return jsonOut({ ok: q.ok, action: "quote-node", quote: q }, { ok: q.ok }, max); }
      if (params.action === "unlock" || params.action === "upgrade") { if (!params.nodeId) throw new Error(`${params.action} requires nodeId`); const q = quote(graph, state, params.nodeId, ex, settings); if (!q.ok) throw new Error(q.errors.join("; ")); if (!q.afford) throw new Error("Insufficient reward points"); if (q.price.amount > 0) { state.currency.balances = deductPrice(state.currency.balances, q.price, ex); state.currency.lifetimeSpent = addPoints(state.currency.lifetimeSpent, q.price.amount, q.price.pointLevel, ex); } state.storyGraph.unlockedNodes.push(params.nodeId); if (q.node.nodeKind === "abilityBase" && !state.storyGraph.unlockedAbilityBases.includes(params.nodeId)) state.storyGraph.unlockedAbilityBases.push(params.nodeId); const tx = { id: id(params.action), type: params.action, state: "completed", nodeId: params.nodeId, nodeName: q.node.name, price: q.price, createdAt: now(), completedAt: now(), cardModuleUpdates: params.cardModuleUpdates || [], memoryUpdates: params.memoryUpdates || [] }; state.transactions.push(tx); state.auditLog.push({ id: id("audit"), at: now(), action: params.action, nodeId: params.nodeId, transactionId: tx.id }); const p = persist(file, state, params); return jsonByMode(params, { ok: true, action: params.action, transaction: tx, reminder: "life_tree_edit updates tree ledger only; use card_edit for concrete modules and memory/world-history.md.", dryRun: !!params.dryRun }, { ok: true, action: params.action, nodeId: params.nodeId, dryRun: !!params.dryRun }, { ok: true, action: params.action, nodeId: params.nodeId, nodeName: q.node.name, price: q.price, transaction: transactionSummary(tx), state: stateSummary(state), dryRun: !!params.dryRun }, { ok: true, ...p }, max); }
      if (params.action === "self-achieve") { if (!params.nodeId) throw new Error("self-achieve requires nodeId"); if (!params.evidenceRef) throw new Error("self-achieve requires evidenceRef"); const node = nodeById(graph, params.nodeId); if (!node) throw new Error("node not found: " + params.nodeId); const v = validateNode(node, settings); if (!v.ok) throw new Error(v.errors.join("; ")); if (!state.storyGraph.selfAchievedNodes.includes(params.nodeId)) state.storyGraph.selfAchievedNodes.push(params.nodeId); if (!state.storyGraph.unlockedNodes.includes(params.nodeId)) state.storyGraph.unlockedNodes.push(params.nodeId); if (node.nodeKind === "abilityBase" && !state.storyGraph.unlockedAbilityBases.includes(params.nodeId)) state.storyGraph.unlockedAbilityBases.push(params.nodeId); const tx = { id: id("self-achieve"), type: "self-achieve", state: "completed", nodeId: params.nodeId, nodeName: node.name, evidenceRef: params.evidenceRef, reason: params.reason, createdAt: now(), completedAt: now(), cardModuleUpdates: params.cardModuleUpdates || [], memoryUpdates: params.memoryUpdates || [] }; state.transactions.push(tx); const p = persist(file, state, params); return jsonByMode(params, { ok: true, action: "self-achieve", transaction: tx, dryRun: !!params.dryRun }, { ok: true, action: "self-achieve", nodeId: params.nodeId, dryRun: !!params.dryRun }, { ok: true, action: "self-achieve", nodeId: params.nodeId, nodeName: node.name, transaction: transactionSummary(tx), state: stateSummary(state), dryRun: !!params.dryRun }, { ok: true, ...p }, max); }
      if (params.action === "grant-points") { const sourceType = params.sourceType || ""; if (!ALLOWED_GRANT_SOURCES.has(sourceType)) throw new Error("invalid grant sourceType: " + sourceType); if (!params.eventRef) throw new Error("grant-points requires eventRef"); for (const hint of FORBIDDEN_GRANT_HINTS) if ((params.reason || "").includes(hint)) throw new Error("Forbidden reward point source: " + hint); const amount = Math.floor(params.amount || 0), level = Math.floor(params.pointLevel || 1); state.currency.balances = addPoints(state.currency.balances, amount, level, ex); state.currency.lifetimeEarned = addPoints(state.currency.lifetimeEarned, amount, level, ex); const tx = { id: id("grant"), type: "grant-points", state: "completed", sourceType, amount, pointLevel: level, display: `${amount}个${pointName(level)}`, reason: params.reason, eventRef: params.eventRef, createdAt: now(), completedAt: now() }; state.transactions.push(tx); const p = persist(file, state, params); return jsonByMode(params, { ok: true, action: "grant-points", transaction: tx, dryRun: !!params.dryRun }, { ok: true, action: "grant-points", amount, pointLevel: level, dryRun: !!params.dryRun }, { ok: true, action: "grant-points", transaction: transactionSummary(tx), state: stateSummary(state), dryRun: !!params.dryRun }, { ok: true, ...p }, max); }
      if (params.action === "audit-source") { if (!params.sourceAudit) throw new Error("audit-source requires sourceAudit"); state.sourceAudits.push({ id: params.sourceAudit.id || id("source"), ...params.sourceAudit, updatedAt: now() }); const p = persist(file, state, params); return jsonByMode(params, { ok: true, action: "audit-source", sourceAudits: state.sourceAudits, dryRun: !!params.dryRun }, { ok: true, action: "audit-source", sourceAuditId: params.sourceAudit.id || null, dryRun: !!params.dryRun }, { ok: true, action: "audit-source", sourceAuditCount: state.sourceAudits.length, latestSourceAudit: state.sourceAudits[state.sourceAudits.length - 1], dryRun: !!params.dryRun }, { ok: true, ...p }, max); }
      if (params.action === "validate") { const vg = validateGraph(graph, settings); return jsonOut({ ok: vg.ok, action: "validate", graph: vg, state: { ok: state.schema === "rp-life-system-tree-state-v1", schema: state.schema } }, { ok: vg.ok }, max); }
      throw new Error("Unknown action: " + (params.action as Action));
    } catch (err: any) { return fail(err.message || String(err), max); }
  } });
}
